[workspace]
authors = ["codewithprags <pragati.dwivedi@outlook.com>"]
channels = ["conda-forge"]
name = "VIDO PROJECT FILES"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
ipykernel = ">=6.30.1,<7"
pip = ">=25.2,<26"
pandas = ">=2.3.1,<3"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"
seaborn = ">=0.13.2,<0.14"
biopython = ">=1.85,<2"
